# Generated by Django 4.2 on 2025-10-16 14:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Point_vente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("p1", models.BigIntegerField(verbose_name="fid")),
                (
                    "p2",
                    models.CharField(
                        max_length=254, verbose_name=".IDENTIFICATION De la rue"
                    ),
                ),
                ("p3", models.DateField(verbose_name="Enter a date and time")),
                (
                    "p4",
                    models.CharField(
                        max_length=254, verbose_name="Conditions Climatiques:"
                    ),
                ),
                (
                    "p5",
                    models.CharField(
                        max_length=254, verbose_name="_Coordonnées : _latitude"
                    ),
                ),
                (
                    "p6",
                    models.CharField(
                        max_length=254, verbose_name="_Coordonnées : _longitude"
                    ),
                ),
                (
                    "p7",
                    models.CharField(
                        max_length=254, verbose_name="_Coordonnées : _altitude"
                    ),
                ),
                ("p8", models.CharField(max_length=254, verbose_name="2. Genre")),
                (
                    "p9",
                    models.CharField(
                        max_length=254,
                        verbose_name="2. Personne Vivant avec un Handicap",
                    ),
                ),
                (
                    "p10",
                    models.CharField(
                        max_length=254, verbose_name="2. Poste Fixe ou Mobile"
                    ),
                ),
                (
                    "p11",
                    models.CharField(
                        max_length=254, verbose_name="2. Apparence du lieu de commerce"
                    ),
                ),
                (
                    "p12",
                    models.CharField(
                        max_length=254, verbose_name="2. Occupation de l’espace Public"
                    ),
                ),
                (
                    "p13",
                    models.CharField(
                        max_length=254,
                        verbose_name="2. Type d' entrave sur la mobilité",
                    ),
                ),
                (
                    "p14",
                    models.CharField(
                        max_length=254,
                        verbose_name="2. Surface de vente/ lieu de vente :",
                    ),
                ),
                (
                    "p15",
                    models.CharField(
                        max_length=254,
                        verbose_name="2. Les principaux biens ou services vendus :",
                    ),
                ),
                ("p16", models.CharField(max_length=254, verbose_name="3. Age")),
                (
                    "p17",
                    models.CharField(max_length=254, verbose_name="3. Nationalité"),
                ),
                (
                    "p18",
                    models.CharField(
                        max_length=254,
                        verbose_name="3. Quel est votre diplôme le plus élevé ?",
                    ),
                ),
                (
                    "p19",
                    models.CharField(
                        max_length=254,
                        verbose_name="3. Quelle (s) langue (s) parlez-vous couramment ?",
                    ),
                ),
                (
                    "p20",
                    models.CharField(
                        max_length=254, verbose_name="3. Statut matrimonial :"
                    ),
                ),
                (
                    "p21",
                    models.CharField(
                        max_length=254,
                        verbose_name="3. Etes vous le chef de votre famille ?",
                    ),
                ),
                (
                    "p22",
                    models.CharField(
                        max_length=254,
                        verbose_name="3. Combien d’enfants sont à votre charge  :",
                    ),
                ),
                (
                    "p23",
                    models.CharField(
                        max_length=254,
                        verbose_name="3. Amenez-vous régulièrement vos enfants avec vous au travail ?",
                    ),
                ),
                (
                    "p24",
                    models.CharField(
                        max_length=254,
                        verbose_name="3. Si oui, combien d’enfants amenez-vous régulièrement au travail ?",
                    ),
                ),
                (
                    "p25",
                    models.CharField(
                        max_length=254,
                        verbose_name="3. Appareil de communication utilisé :",
                    ),
                ),
                (
                    "p26",
                    models.CharField(
                        max_length=254,
                        verbose_name="4  Est-ce votre activité principale ?",
                    ),
                ),
                (
                    "p27",
                    models.CharField(
                        max_length=254,
                        verbose_name="4  Depuis combien de temps exercez-vous cette activité économique ?",
                    ),
                ),
                (
                    "p28",
                    models.CharField(
                        max_length=254,
                        verbose_name="4  A quelle heure arrivez-vous habituellement à votre lieu de vente ?",
                    ),
                ),
                (
                    "p29",
                    models.CharField(
                        max_length=254,
                        verbose_name="4  A quelle heure arrêtez-vous habituellement la vente ?",
                    ),
                ),
                (
                    "p30",
                    models.CharField(
                        max_length=254,
                        verbose_name="4  Pourquoi avez-vous choisi ce lieu de vente",
                    ),
                ),
                (
                    "p31",
                    models.CharField(
                        max_length=254,
                        verbose_name="4  Occupez-vous le même lieu de vente / espace commercial  chaque jour?",
                    ),
                ),
                (
                    "p32",
                    models.CharField(
                        max_length=254,
                        verbose_name="4  Si oui,  payez-vous pour occuper ce lieu de vente / espace commercial ?",
                    ),
                ),
                (
                    "p33",
                    models.CharField(
                        max_length=254,
                        verbose_name="4  Si oui, auprès de qui payez-vous  la location de votre lieu de vente /espace commercial ?",
                    ),
                ),
                (
                    "p34",
                    models.CharField(
                        max_length=254,
                        verbose_name="4  Si oui, à quelle fréquence payez-vous la location de votre lieu de vente /espace commercial ?",
                    ),
                ),
                (
                    "p35",
                    models.CharField(
                        max_length=254,
                        verbose_name="4  Si oui, quel est le mode de paiement la location de votre lieu de vente /espace commercial ?",
                    ),
                ),
                (
                    "p36",
                    models.BigIntegerField(
                        verbose_name="4  Si oui, quel est montant de la location de votre lieu de vente /espace commercial ?"
                    ),
                ),
                (
                    "p37",
                    models.CharField(
                        max_length=254,
                        verbose_name="4 quel est le type de matériel de construction de votre espace commercial ?",
                    ),
                ),
                (
                    "p38",
                    models.CharField(
                        max_length=254,
                        verbose_name="4  Avez-vous accès à l’eau courante/ eau potable ?",
                    ),
                ),
                (
                    "p39",
                    models.CharField(
                        max_length=254,
                        verbose_name="4  Si oui, quelle est la distance entre votre point de vente et le point d’eau le plus proche? (en mètres)",
                    ),
                ),
                (
                    "p40",
                    models.CharField(
                        max_length=254,
                        verbose_name="4  Si oui, précisez l’emplacement / le  lieu :",
                    ),
                ),
                (
                    "p41",
                    models.CharField(
                        max_length=254,
                        verbose_name="4  Avez-vous régulièrement accès à des toilettes aménagées ?",
                    ),
                ),
                (
                    "p42",
                    models.CharField(
                        max_length=254,
                        verbose_name="4  Si oui, qui est le propriétaire des toilettes aménagées que vous utilisez habituellement ?",
                    ),
                ),
                (
                    "p43",
                    models.CharField(
                        max_length=254,
                        verbose_name="4  Si oui, quelle est la distance entre votre point de vente et les toilettes aménagées les plus proches ? (en mètres)?",
                    ),
                ),
                (
                    "p44",
                    models.CharField(
                        max_length=254,
                        verbose_name="4  Existe-t-il des bacs à ordures aménagés aux alentours de votre point de vente ?",
                    ),
                ),
                (
                    "p45",
                    models.CharField(
                        max_length=254,
                        verbose_name="4  Si oui, quelle est la distance entre votre point de vente et le bacs à ordure aménagé le plus proche ?",
                    ),
                ),
                (
                    "p46",
                    models.CharField(
                        max_length=254, verbose_name="4  Si oui, précisez le lieu :"
                    ),
                ),
                (
                    "p47",
                    models.CharField(
                        max_length=254,
                        verbose_name="4  Avez-vous  besoin d’électricité  pour mener votre activité commerciale?",
                    ),
                ),
                (
                    "p48",
                    models.CharField(
                        max_length=254,
                        verbose_name="4  si oui Avez-vous accès à l’électricité ?",
                    ),
                ),
                (
                    "p49",
                    models.CharField(
                        max_length=254,
                        verbose_name="4  Si oui, avez-vous un abonnement individuel ?",
                    ),
                ),
                (
                    "p50",
                    models.CharField(
                        max_length=254,
                        verbose_name="4  A quel moment de la journée mener vous votre activité commerciale ?",
                    ),
                ),
                (
                    "p51",
                    models.CharField(
                        max_length=254,
                        verbose_name="4  Existe-t-il des lampadaires fonctionnels à coté de vos points de vente ?",
                    ),
                ),
                (
                    "p52",
                    models.CharField(
                        max_length=254,
                        verbose_name="4  Avez-vous besoin d’un magasin/lieu de stockage de vos produits ?",
                    ),
                ),
                (
                    "p53",
                    models.CharField(
                        max_length=254,
                        verbose_name="4  Si oui, disposez-vous déjà d’un magasin/lieu de stockage?",
                    ),
                ),
                (
                    "p54",
                    models.CharField(
                        max_length=254,
                        verbose_name="4  Si oui, quelle est la distance entre votre point de vente et votre magasin/lieu de stockage",
                    ),
                ),
                (
                    "p55",
                    models.CharField(
                        max_length=254,
                        verbose_name="4  si oui, précisez l’emplacement/lieu",
                    ),
                ),
                (
                    "p56",
                    models.CharField(
                        max_length=254,
                        verbose_name="4  Comment est fait le choix du lieu de vente au quotidien ?",
                    ),
                ),
                (
                    "p57",
                    models.CharField(
                        max_length=254,
                        verbose_name="4  Dans quel quartier vivez-vous actuellement ?",
                    ),
                ),
                (
                    "p58",
                    models.CharField(
                        max_length=254,
                        verbose_name="4  Quel est votre moyen de transport habituel pour venir sur votre lieu de commerce ?",
                    ),
                ),
                (
                    "p59",
                    models.CharField(
                        max_length=254,
                        verbose_name="5. Vendez-vous toujours les mêmes produits et services?",
                    ),
                ),
                (
                    "p60",
                    models.CharField(
                        max_length=254,
                        verbose_name="5. Si non, citez les autres produits et services que vous commercialisez/vendez ?",
                    ),
                ),
                (
                    "p61",
                    models.CharField(
                        max_length=254,
                        verbose_name="5. Utilisez-vous l’un des services suivants dans votre activité commerciale ?",
                    ),
                ),
                (
                    "p62",
                    models.CharField(
                        max_length=254,
                        verbose_name="5. Quels sont vos principaux clients :",
                    ),
                ),
                (
                    "p63",
                    models.CharField(
                        max_length=254,
                        verbose_name="5. Quelle sont les stratégies que vous utilisez le plus pour convaincre vos clients d’acheter vos produits /services ?",
                    ),
                ),
                (
                    "p64",
                    models.CharField(
                        max_length=254,
                        verbose_name="5. Ou obtenez-vous les produits que vous vendez ?",
                    ),
                ),
                (
                    "p65",
                    models.BigIntegerField(
                        verbose_name="5. Quel est en moyenne le montant de vos ventes chaque semaine?"
                    ),
                ),
                (
                    "p66",
                    models.CharField(
                        max_length=254,
                        verbose_name="6. Payez-vous une taxe pour faire du commerce à cet endroit ?",
                    ),
                ),
                (
                    "p67",
                    models.CharField(
                        max_length=254,
                        verbose_name="6. Si oui, à quelle fréquence payez-vous cette taxe ?",
                    ),
                ),
                (
                    "p68",
                    models.CharField(
                        max_length=254,
                        verbose_name="6. Selon la fréquence choisie, à combien s’élève la somme déboursée ?",
                    ),
                ),
                (
                    "p69",
                    models.CharField(
                        max_length=254,
                        verbose_name="6. Quel mode de paiement utilisez-vous pour payer les services liés à cet espace ?",
                    ),
                ),
                (
                    "p70",
                    models.CharField(
                        max_length=254,
                        verbose_name="6. Combien d’autres personnes travaillent avec vous ou vous assistent ? Spécifiez le nombre.",
                    ),
                ),
                (
                    "p71",
                    models.CharField(
                        max_length=254,
                        verbose_name="7. Avez-vous déjà reçu un soutien du gouvernement pour booster votre activité économique  ?",
                    ),
                ),
                (
                    "p72",
                    models.CharField(
                        max_length=254,
                        verbose_name="7. Avez-vous déjà reçu un soutien d’une ONG/ d’un partenaire pour booster votre activité économique ?",
                    ),
                ),
                (
                    "p73",
                    models.CharField(
                        max_length=254,
                        verbose_name="8. Avez-vous déjà subi du harcèlement  sexuel ou des intimidations liés à votre sexe sur votre lieu de vente / dans votre espace commecial?",
                    ),
                ),
                (
                    "p74",
                    models.CharField(
                        max_length=254, verbose_name="8.  Si oui de la part de qui ?"
                    ),
                ),
                (
                    "p75",
                    models.CharField(
                        max_length=254,
                        verbose_name="8.  Avez-vous déjà été victime de confiscation ou de violence de la part de la police ?",
                    ),
                ),
                (
                    "p76",
                    models.CharField(
                        max_length=254,
                        verbose_name="8.  Si oui, expliquez dans quel contexte",
                    ),
                ),
                (
                    "p77",
                    models.CharField(
                        max_length=254,
                        verbose_name="8.  Avez-vous déjà été victime de confiscation ou de violence de la part des agents communaux?",
                    ),
                ),
                (
                    "p78",
                    models.CharField(
                        max_length=254,
                        verbose_name="8.  Si oui, expliquez dans quel contexte",
                    ),
                ),
                (
                    "p79",
                    models.CharField(
                        max_length=254,
                        verbose_name="8.  Avez-vous déjà reçu des amendes ou des avertissements pour obstruction de la voie publique",
                    ),
                ),
                (
                    "p80",
                    models.CharField(
                        max_length=254,
                        verbose_name="8.  Avez-vous déjà été victime des coups de vol sur votre comptoir ?",
                    ),
                ),
                (
                    "p81",
                    models.CharField(
                        max_length=254,
                        verbose_name="8.  Craignez-vous d’être expulsé de votre lieu de vente ?",
                    ),
                ),
                (
                    "p82",
                    models.CharField(
                        max_length=254, verbose_name="8.  Si oui, pourquoi ?"
                    ),
                ),
                (
                    "p83",
                    models.CharField(
                        max_length=254,
                        verbose_name="8.   Ressentez-vous des différences de traitement par rapport à votre sexe ?",
                    ),
                ),
                (
                    "p84",
                    models.CharField(
                        max_length=254, verbose_name="8.  Si oui, expliquez"
                    ),
                ),
                (
                    "p85",
                    models.CharField(
                        max_length=254,
                        verbose_name="9.  Êtes-vous membre d’une organisation ou d’une association de commerçants de rue ?",
                    ),
                ),
                (
                    "p86",
                    models.CharField(
                        max_length=254,
                        verbose_name="9.  Si oui, occupez-vous un poste de responsabilité au sein de cette association",
                    ),
                ),
                (
                    "p87",
                    models.CharField(
                        max_length=254,
                        verbose_name="9.  Etes-vous informé des projets qui visent à améliorer la circulation automobile, à éliminer les inondations ou à construire des boutiques communales dans les rues où vous travaillez ?",
                    ),
                ),
                (
                    "p88",
                    models.CharField(
                        max_length=254, verbose_name="9.  Si oui, citez les"
                    ),
                ),
                (
                    "p89",
                    models.CharField(
                        max_length=254,
                        verbose_name="9.  Si oui, avez-vous été consulté par les porteurs du projet ?",
                    ),
                ),
                (
                    "p90",
                    models.CharField(
                        max_length=254,
                        verbose_name="9.  Avez-vous déjà déposé une plainte / demande à la Commune au sujet de votre activité commerciale ?",
                    ),
                ),
                (
                    "p91",
                    models.CharField(
                        max_length=254,
                        verbose_name="9.  Si oui, avez-vous eu une réponse de la commune à votre plainte ou demande?",
                    ),
                ),
                (
                    "p92",
                    models.CharField(
                        max_length=254,
                        verbose_name="9.  Qu’est ce que vous attendez de vos relations avec la Commune pour votre activité commerciale ?",
                    ),
                ),
                (
                    "p93",
                    models.CharField(
                        max_length=254,
                        verbose_name="9.  Avez-vous déjà déposé une plainte / demande aux services des impôts au sujet de votre activité commerciale ?",
                    ),
                ),
                (
                    "p94",
                    models.CharField(
                        max_length=254,
                        verbose_name="9.  Qu’est ce que vous attendez de vos relations avec les services des impôts pour votre activité commerciale ?",
                    ),
                ),
                (
                    "p95",
                    models.CharField(
                        max_length=254,
                        verbose_name="9.  Si oui, avez-vous eu une réponse des services des impôts à votre plainte ou demande?",
                    ),
                ),
                (
                    "p96",
                    models.CharField(
                        max_length=254,
                        verbose_name="9.  Avez-vous déjà déposé une plainte / demande dans les services de police au sujet de votre activité commerciale ?",
                    ),
                ),
                (
                    "p97",
                    models.CharField(
                        max_length=254,
                        verbose_name="9.  Si oui, avez-vous eu une réponse des services de police à votre plainte ou demande?",
                    ),
                ),
                (
                    "p98",
                    models.CharField(
                        max_length=254,
                        verbose_name="9.  Qu’est ce que vous attendez de vos relations avec les services de police pour votre activité commerciale ?",
                    ),
                ),
                (
                    "p99",
                    models.CharField(
                        max_length=254,
                        verbose_name="9.  Quel est le plus grand problème / défi majeur que vous rencontrez depuis que vous exercez cette activité ?",
                    ),
                ),
                (
                    "p100",
                    models.CharField(
                        max_length=254,
                        verbose_name="9.  Que proposez-vous comme piste de solution pour l’amélioration des conditions des commerçants de rue ?",
                    ),
                ),
                (
                    "p101",
                    models.CharField(
                        max_length=254,
                        verbose_name="9.  Dans le cadre du projet Informa’ll City Move, nous aimerions organiser une base de données des commerçants de rue au centre-ville. Seriez-vous intéressez à figurer dans cette base de données afin de servir de point de contact ?",
                    ),
                ),
                ("p102", models.CharField(max_length=254, verbose_name="9.  Nom :")),
                (
                    "p103",
                    models.CharField(
                        max_length=254, verbose_name="9.  Numéro de téléphone :"
                    ),
                ),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
