# Generated by Django 4.2 on 2025-10-16 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("move", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Point_vente",
        ),
    ]
