# Generated by Django 4.2 on 2025-10-16 14:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("move", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="point_vente",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p1",
            field=models.BigIntegerField(null=True, verbose_name="fid"),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p10",
            field=models.CharField(
                max_length=254, null=True, verbose_name="2. Poste Fixe ou Mobile"
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p100",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="9.  Que proposez-vous comme piste de solution pour l’amélioration des conditions des commerçants de rue ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p101",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="9.  Dans le cadre du projet Informa’ll City Move, nous aimerions organiser une base de données des commerçants de rue au centre-ville. Seriez-vous intéressez à figurer dans cette base de données afin de servir de point de contact ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p102",
            field=models.CharField(max_length=254, null=True, verbose_name="9.  Nom :"),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p103",
            field=models.CharField(
                max_length=254, null=True, verbose_name="9.  Numéro de téléphone :"
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p11",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="2. Apparence du lieu de commerce",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p12",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="2. Occupation de l’espace Public",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p13",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="2. Type d' entrave sur la mobilité",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p14",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="2. Surface de vente/ lieu de vente :",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p15",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="2. Les principaux biens ou services vendus :",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p16",
            field=models.CharField(max_length=254, null=True, verbose_name="3. Age"),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p17",
            field=models.CharField(
                max_length=254, null=True, verbose_name="3. Nationalité"
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p18",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="3. Quel est votre diplôme le plus élevé ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p19",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="3. Quelle (s, null=True) langue (s, null=True) parlez-vous couramment ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p2",
            field=models.CharField(
                max_length=254, null=True, verbose_name=".IDENTIFICATION De la rue"
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p20",
            field=models.CharField(
                max_length=254, null=True, verbose_name="3. Statut matrimonial :"
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p21",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="3. Etes vous le chef de votre famille ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p22",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="3. Combien d’enfants sont à votre charge  :",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p23",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="3. Amenez-vous régulièrement vos enfants avec vous au travail ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p24",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="3. Si oui, combien d’enfants amenez-vous régulièrement au travail ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p25",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="3. Appareil de communication utilisé :",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p26",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="4  Est-ce votre activité principale ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p27",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="4  Depuis combien de temps exercez-vous cette activité économique ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p28",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="4  A quelle heure arrivez-vous habituellement à votre lieu de vente ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p29",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="4  A quelle heure arrêtez-vous habituellement la vente ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p3",
            field=models.DateField(null=True, verbose_name="Enter a date and time"),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p30",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="4  Pourquoi avez-vous choisi ce lieu de vente",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p31",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="4  Occupez-vous le même lieu de vente / espace commercial  chaque jour?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p32",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="4  Si oui,  payez-vous pour occuper ce lieu de vente / espace commercial ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p33",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="4  Si oui, auprès de qui payez-vous  la location de votre lieu de vente /espace commercial ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p34",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="4  Si oui, à quelle fréquence payez-vous la location de votre lieu de vente /espace commercial ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p35",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="4  Si oui, quel est le mode de paiement la location de votre lieu de vente /espace commercial ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p36",
            field=models.BigIntegerField(
                null=True,
                verbose_name="4  Si oui, quel est montant de la location de votre lieu de vente /espace commercial ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p37",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="4 quel est le type de matériel de construction de votre espace commercial ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p38",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="4  Avez-vous accès à l’eau courante/ eau potable ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p39",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="4  Si oui, quelle est la distance entre votre point de vente et le point d’eau le plus proche? (en mètres, null=True)",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p4",
            field=models.CharField(
                max_length=254, null=True, verbose_name="Conditions Climatiques:"
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p40",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="4  Si oui, précisez l’emplacement / le  lieu :",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p41",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="4  Avez-vous régulièrement accès à des toilettes aménagées ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p42",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="4  Si oui, qui est le propriétaire des toilettes aménagées que vous utilisez habituellement ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p43",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="4  Si oui, quelle est la distance entre votre point de vente et les toilettes aménagées les plus proches ? (en mètres, null=True)?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p44",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="4  Existe-t-il des bacs à ordures aménagés aux alentours de votre point de vente ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p45",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="4  Si oui, quelle est la distance entre votre point de vente et le bacs à ordure aménagé le plus proche ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p46",
            field=models.CharField(
                max_length=254, null=True, verbose_name="4  Si oui, précisez le lieu :"
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p47",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="4  Avez-vous  besoin d’électricité  pour mener votre activité commerciale?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p48",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="4  si oui Avez-vous accès à l’électricité ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p49",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="4  Si oui, avez-vous un abonnement individuel ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p5",
            field=models.CharField(
                max_length=254, null=True, verbose_name="_Coordonnées : _latitude"
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p50",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="4  A quel moment de la journée mener vous votre activité commerciale ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p51",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="4  Existe-t-il des lampadaires fonctionnels à coté de vos points de vente ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p52",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="4  Avez-vous besoin d’un magasin/lieu de stockage de vos produits ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p53",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="4  Si oui, disposez-vous déjà d’un magasin/lieu de stockage?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p54",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="4  Si oui, quelle est la distance entre votre point de vente et votre magasin/lieu de stockage",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p55",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="4  si oui, précisez l’emplacement/lieu",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p56",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="4  Comment est fait le choix du lieu de vente au quotidien ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p57",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="4  Dans quel quartier vivez-vous actuellement ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p58",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="4  Quel est votre moyen de transport habituel pour venir sur votre lieu de commerce ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p59",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="5. Vendez-vous toujours les mêmes produits et services?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p6",
            field=models.CharField(
                max_length=254, null=True, verbose_name="_Coordonnées : _longitude"
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p60",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="5. Si non, citez les autres produits et services que vous commercialisez/vendez ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p61",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="5. Utilisez-vous l’un des services suivants dans votre activité commerciale ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p62",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="5. Quels sont vos principaux clients :",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p63",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="5. Quelle sont les stratégies que vous utilisez le plus pour convaincre vos clients d’acheter vos produits /services ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p64",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="5. Ou obtenez-vous les produits que vous vendez ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p65",
            field=models.BigIntegerField(
                null=True,
                verbose_name="5. Quel est en moyenne le montant de vos ventes chaque semaine?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p66",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="6. Payez-vous une taxe pour faire du commerce à cet endroit ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p67",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="6. Si oui, à quelle fréquence payez-vous cette taxe ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p68",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="6. Selon la fréquence choisie, à combien s’élève la somme déboursée ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p69",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="6. Quel mode de paiement utilisez-vous pour payer les services liés à cet espace ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p7",
            field=models.CharField(
                max_length=254, null=True, verbose_name="_Coordonnées : _altitude"
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p70",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="6. Combien d’autres personnes travaillent avec vous ou vous assistent ? Spécifiez le nombre.",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p71",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="7. Avez-vous déjà reçu un soutien du gouvernement pour booster votre activité économique  ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p72",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="7. Avez-vous déjà reçu un soutien d’une ONG/ d’un partenaire pour booster votre activité économique ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p73",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="8. Avez-vous déjà subi du harcèlement  sexuel ou des intimidations liés à votre sexe sur votre lieu de vente / dans votre espace commecial?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p74",
            field=models.CharField(
                max_length=254, null=True, verbose_name="8.  Si oui de la part de qui ?"
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p75",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="8.  Avez-vous déjà été victime de confiscation ou de violence de la part de la police ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p76",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="8.  Si oui, expliquez dans quel contexte",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p77",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="8.  Avez-vous déjà été victime de confiscation ou de violence de la part des agents communaux?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p78",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="8.  Si oui, expliquez dans quel contexte",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p79",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="8.  Avez-vous déjà reçu des amendes ou des avertissements pour obstruction de la voie publique",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p8",
            field=models.CharField(max_length=254, null=True, verbose_name="2. Genre"),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p80",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="8.  Avez-vous déjà été victime des coups de vol sur votre comptoir ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p81",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="8.  Craignez-vous d’être expulsé de votre lieu de vente ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p82",
            field=models.CharField(
                max_length=254, null=True, verbose_name="8.  Si oui, pourquoi ?"
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p83",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="8.   Ressentez-vous des différences de traitement par rapport à votre sexe ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p84",
            field=models.CharField(
                max_length=254, null=True, verbose_name="8.  Si oui, expliquez"
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p85",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="9.  Êtes-vous membre d’une organisation ou d’une association de commerçants de rue ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p86",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="9.  Si oui, occupez-vous un poste de responsabilité au sein de cette association",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p87",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="9.  Etes-vous informé des projets qui visent à améliorer la circulation automobile, à éliminer les inondations ou à construire des boutiques communales dans les rues où vous travaillez ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p88",
            field=models.CharField(
                max_length=254, null=True, verbose_name="9.  Si oui, citez les"
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p89",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="9.  Si oui, avez-vous été consulté par les porteurs du projet ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p9",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="2. Personne Vivant avec un Handicap",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p90",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="9.  Avez-vous déjà déposé une plainte / demande à la Commune au sujet de votre activité commerciale ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p91",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="9.  Si oui, avez-vous eu une réponse de la commune à votre plainte ou demande?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p92",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="9.  Qu’est ce que vous attendez de vos relations avec la Commune pour votre activité commerciale ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p93",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="9.  Avez-vous déjà déposé une plainte / demande aux services des impôts au sujet de votre activité commerciale ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p94",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="9.  Qu’est ce que vous attendez de vos relations avec les services des impôts pour votre activité commerciale ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p95",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="9.  Si oui, avez-vous eu une réponse des services des impôts à votre plainte ou demande?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p96",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="9.  Avez-vous déjà déposé une plainte / demande dans les services de police au sujet de votre activité commerciale ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p97",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="9.  Si oui, avez-vous eu une réponse des services de police à votre plainte ou demande?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p98",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="9.  Qu’est ce que vous attendez de vos relations avec les services de police pour votre activité commerciale ?",
            ),
        ),
        migrations.AlterField(
            model_name="point_vente",
            name="p99",
            field=models.CharField(
                max_length=254,
                null=True,
                verbose_name="9.  Quel est le plus grand problème / défi majeur que vous rencontrez depuis que vous exercez cette activité ?",
            ),
        ),
    ]
