from django.contrib.gis.db import models
from django.contrib.gis.geos import Point

class Point_vente(models.Model):
    p1 = models.BigIntegerField(verbose_name="fid", null=True)
    p2 = models.CharField(max_length=254, verbose_name=".IDENTIFICATION De la rue", null=True)
    p3 = models.DateField(verbose_name="Enter a date and time", null=True)
    p4 = models.CharField(max_length=254, verbose_name="Conditions Climatiques:", null=True)
    p5 = models.CharField(max_length=254, verbose_name="_Coordonnées : _latitude", null=True)
    p6 = models.CharField(max_length=254, verbose_name="_Coordonnées : _longitude", null=True)
    p7 = models.CharField(max_length=254, verbose_name="_Coordonnées : _altitude", null=True)
    p8 = models.CharField(max_length=254, verbose_name="2. Genre", null=True)
    p9 = models.CharField(max_length=254, verbose_name="2. Personne Vivant avec un Handicap", null=True)
    p10 = models.CharField(max_length=254, verbose_name="2. Poste Fixe ou Mobile", null=True)
    p11 = models.CharField(max_length=254, verbose_name="2. Apparence du lieu de commerce", null=True)
    p12 = models.CharField(max_length=254, verbose_name="2. Occupation de l’espace Public", null=True)
    p13 = models.CharField(max_length=254, verbose_name="2. Type d' entrave sur la mobilité", null=True)
    p14 = models.CharField(max_length=254, verbose_name="2. Surface de vente/ lieu de vente :", null=True)
    p15 = models.CharField(max_length=254, verbose_name="2. Les principaux biens ou services vendus :", null=True)
    p16 = models.CharField(max_length=254, verbose_name="3. Age", null=True)
    p17 = models.CharField(max_length=254, verbose_name="3. Nationalité", null=True)
    p18 = models.CharField(max_length=254, verbose_name="3. Quel est votre diplôme le plus élevé ?", null=True)
    p19 = models.CharField(max_length=254, verbose_name="3. Quelle (s) langue (s) parlez-vous couramment ?", null=True)
    p20 = models.CharField(max_length=254, verbose_name="3. Statut matrimonial :", null=True)
    p21 = models.CharField(max_length=254, verbose_name="3. Etes vous le chef de votre famille ?", null=True)
    p22 = models.CharField(max_length=254, verbose_name="3. Combien d’enfants sont à votre charge  :", null=True)
    p23 = models.CharField(max_length=254, verbose_name="3. Amenez-vous régulièrement vos enfants avec vous au travail ?", null=True)
    p24 = models.CharField(max_length=254, verbose_name="3. Si oui, combien d’enfants amenez-vous régulièrement au travail ?", null=True)
    p25 = models.CharField(max_length=254, verbose_name="3. Appareil de communication utilisé :", null=True)
    p26 = models.CharField(max_length=254, verbose_name="4  Est-ce votre activité principale ?", null=True)
    p27 = models.CharField(max_length=254, verbose_name="4  Depuis combien de temps exercez-vous cette activité économique ?", null=True)
    p28 = models.CharField(max_length=254, verbose_name="4  A quelle heure arrivez-vous habituellement à votre lieu de vente ?", null=True)
    p29 = models.CharField(max_length=254, verbose_name="4  A quelle heure arrêtez-vous habituellement la vente ?", null=True)
    p30 = models.CharField(max_length=254, verbose_name="4  Pourquoi avez-vous choisi ce lieu de vente", null=True)
    p31 = models.CharField(max_length=254, verbose_name="4  Occupez-vous le même lieu de vente / espace commercial  chaque jour?", null=True)
    p32 = models.CharField(max_length=254, verbose_name="4  Si oui,  payez-vous pour occuper ce lieu de vente / espace commercial ?", null=True)
    p33 = models.CharField(max_length=254, verbose_name="4  Si oui, auprès de qui payez-vous  la location de votre lieu de vente /espace commercial ?", null=True)
    p34 = models.CharField(max_length=254, verbose_name="4  Si oui, à quelle fréquence payez-vous la location de votre lieu de vente /espace commercial ?", null=True)
    p35 = models.CharField(max_length=254, verbose_name="4  Si oui, quel est le mode de paiement la location de votre lieu de vente /espace commercial ?", null=True)
    p36 = models.BigIntegerField(verbose_name="4  Si oui, quel est montant de la location de votre lieu de vente /espace commercial ?", null=True)
    p37 = models.CharField(max_length=254, verbose_name="4 quel est le type de matériel de construction de votre espace commercial ?", null=True)
    p38 = models.CharField(max_length=254, verbose_name="4  Avez-vous accès à l’eau courante/ eau potable ?", null=True)
    p39 = models.CharField(max_length=254, verbose_name="4  Si oui, quelle est la distance entre votre point de vente et le point d’eau le plus proche? (en mètres)", null=True)
    p40 = models.CharField(max_length=254, verbose_name="4  Si oui, précisez l’emplacement / le  lieu :", null=True)
    p41 = models.CharField(max_length=254, verbose_name="4  Avez-vous régulièrement accès à des toilettes aménagées ?", null=True)
    p42 = models.CharField(max_length=254, verbose_name="4  Si oui, qui est le propriétaire des toilettes aménagées que vous utilisez habituellement ?", null=True)
    p43 = models.CharField(max_length=254, verbose_name="4  Si oui, quelle est la distance entre votre point de vente et les toilettes aménagées les plus proches ? (en mètres)?", null=True)
    p44 = models.CharField(max_length=254, verbose_name="4  Existe-t-il des bacs à ordures aménagés aux alentours de votre point de vente ?", null=True)
    p45 = models.CharField(max_length=254, verbose_name="4  Si oui, quelle est la distance entre votre point de vente et le bacs à ordure aménagé le plus proche ?", null=True)
    p46 = models.CharField(max_length=254, verbose_name="4  Si oui, précisez le lieu :", null=True)
    p47 = models.CharField(max_length=254, verbose_name="4  Avez-vous  besoin d’électricité  pour mener votre activité commerciale?", null=True)
    p48 = models.CharField(max_length=254, verbose_name="4  si oui Avez-vous accès à l’électricité ?", null=True)
    p49 = models.CharField(max_length=254, verbose_name="4  Si oui, avez-vous un abonnement individuel ?", null=True)
    p50 = models.CharField(max_length=254, verbose_name="4  A quel moment de la journée mener vous votre activité commerciale ?", null=True)
    p51 = models.CharField(max_length=254, verbose_name="4  Existe-t-il des lampadaires fonctionnels à coté de vos points de vente ?", null=True)
    p52 = models.CharField(max_length=254, verbose_name="4  Avez-vous besoin d’un magasin/lieu de stockage de vos produits ?", null=True)
    p53 = models.CharField(max_length=254, verbose_name="4  Si oui, disposez-vous déjà d’un magasin/lieu de stockage?", null=True)
    p54 = models.CharField(max_length=254, verbose_name="4  Si oui, quelle est la distance entre votre point de vente et votre magasin/lieu de stockage", null=True)
    p55 = models.CharField(max_length=254, verbose_name="4  si oui, précisez l’emplacement/lieu", null=True)
    p56 = models.CharField(max_length=254, verbose_name="4  Comment est fait le choix du lieu de vente au quotidien ?", null=True)
    p57 = models.CharField(max_length=254, verbose_name="4  Dans quel quartier vivez-vous actuellement ?", null=True)
    p58 = models.CharField(max_length=254, verbose_name="4  Quel est votre moyen de transport habituel pour venir sur votre lieu de commerce ?", null=True)
    p59 = models.CharField(max_length=254, verbose_name="5. Vendez-vous toujours les mêmes produits et services?", null=True)
    p60 = models.CharField(max_length=254, verbose_name="5. Si non, citez les autres produits et services que vous commercialisez/vendez ?", null=True)
    p61 = models.CharField(max_length=254, verbose_name="5. Utilisez-vous l’un des services suivants dans votre activité commerciale ?", null=True)
    p62 = models.CharField(max_length=254, verbose_name="5. Quels sont vos principaux clients :", null=True)
    p63 = models.CharField(max_length=254, verbose_name="5. Quelle sont les stratégies que vous utilisez le plus pour convaincre vos clients d’acheter vos produits /services ?", null=True)
    p64 = models.CharField(max_length=254, verbose_name="5. Ou obtenez-vous les produits que vous vendez ?", null=True)
    p65 = models.BigIntegerField(verbose_name="5. Quel est en moyenne le montant de vos ventes chaque semaine?", null=True)
    p66 = models.CharField(max_length=254, verbose_name="6. Payez-vous une taxe pour faire du commerce à cet endroit ?", null=True)
    p67 = models.CharField(max_length=254, verbose_name="6. Si oui, à quelle fréquence payez-vous cette taxe ?", null=True)
    p68 = models.CharField(max_length=254, verbose_name="6. Selon la fréquence choisie, à combien s’élève la somme déboursée ?", null=True)
    p69 = models.CharField(max_length=254, verbose_name="6. Quel mode de paiement utilisez-vous pour payer les services liés à cet espace ?", null=True)
    p70 = models.CharField(max_length=254, verbose_name="6. Combien d’autres personnes travaillent avec vous ou vous assistent ? Spécifiez le nombre.", null=True)
    p71 = models.CharField(max_length=254, verbose_name="7. Avez-vous déjà reçu un soutien du gouvernement pour booster votre activité économique  ?", null=True)
    p72 = models.CharField(max_length=254, verbose_name="7. Avez-vous déjà reçu un soutien d’une ONG/ d’un partenaire pour booster votre activité économique ?", null=True)
    p73 = models.CharField(max_length=254, verbose_name="8. Avez-vous déjà subi du harcèlement  sexuel ou des intimidations liés à votre sexe sur votre lieu de vente / dans votre espace commecial?", null=True)
    p74 = models.CharField(max_length=254, verbose_name="8.  Si oui de la part de qui ?", null=True)
    p75 = models.CharField(max_length=254, verbose_name="8.  Avez-vous déjà été victime de confiscation ou de violence de la part de la police ?", null=True)
    p76 = models.CharField(max_length=254, verbose_name="8.  Si oui, expliquez dans quel contexte", null=True)
    p77 = models.CharField(max_length=254, verbose_name="8.  Avez-vous déjà été victime de confiscation ou de violence de la part des agents communaux?", null=True)
    p78 = models.CharField(max_length=254, verbose_name="8.  Si oui, expliquez dans quel contexte", null=True)
    p79 = models.CharField(max_length=254, verbose_name="8.  Avez-vous déjà reçu des amendes ou des avertissements pour obstruction de la voie publique", null=True)
    p80 = models.CharField(max_length=254, verbose_name="8.  Avez-vous déjà été victime des coups de vol sur votre comptoir ?", null=True)
    p81 = models.CharField(max_length=254, verbose_name="8.  Craignez-vous d’être expulsé de votre lieu de vente ?", null=True)
    p82 = models.CharField(max_length=254, verbose_name="8.  Si oui, pourquoi ?", null=True)
    p83 = models.CharField(max_length=254, verbose_name="8.   Ressentez-vous des différences de traitement par rapport à votre sexe ?", null=True)
    p84 = models.CharField(max_length=254, verbose_name="8.  Si oui, expliquez", null=True)
    p85 = models.CharField(max_length=254, verbose_name="9.  Êtes-vous membre d’une organisation ou d’une association de commerçants de rue ?", null=True)
    p86 = models.CharField(max_length=254, verbose_name="9.  Si oui, occupez-vous un poste de responsabilité au sein de cette association", null=True)
    p87 = models.CharField(max_length=254, verbose_name="9.  Etes-vous informé des projets qui visent à améliorer la circulation automobile, à éliminer les inondations ou à construire des boutiques communales dans les rues où vous travaillez ?", null=True)
    p88 = models.CharField(max_length=254, verbose_name="9.  Si oui, citez les", null=True)
    p89 = models.CharField(max_length=254, verbose_name="9.  Si oui, avez-vous été consulté par les porteurs du projet ?", null=True)
    p90 = models.CharField(max_length=254, verbose_name="9.  Avez-vous déjà déposé une plainte / demande à la Commune au sujet de votre activité commerciale ?", null=True)
    p91 = models.CharField(max_length=254, verbose_name="9.  Si oui, avez-vous eu une réponse de la commune à votre plainte ou demande?", null=True)
    p92 = models.CharField(max_length=254, verbose_name="9.  Qu’est ce que vous attendez de vos relations avec la Commune pour votre activité commerciale ?", null=True)
    p93 = models.CharField(max_length=254, verbose_name="9.  Avez-vous déjà déposé une plainte / demande aux services des impôts au sujet de votre activité commerciale ?", null=True)
    p94 = models.CharField(max_length=254, verbose_name="9.  Qu’est ce que vous attendez de vos relations avec les services des impôts pour votre activité commerciale ?", null=True)
    p95 = models.CharField(max_length=254, verbose_name="9.  Si oui, avez-vous eu une réponse des services des impôts à votre plainte ou demande?", null=True)
    p96 = models.CharField(max_length=254, verbose_name="9.  Avez-vous déjà déposé une plainte / demande dans les services de police au sujet de votre activité commerciale ?", null=True)
    p97 = models.CharField(max_length=254, verbose_name="9.  Si oui, avez-vous eu une réponse des services de police à votre plainte ou demande?", null=True)
    p98 = models.CharField(max_length=254, verbose_name="9.  Qu’est ce que vous attendez de vos relations avec les services de police pour votre activité commerciale ?", null=True)
    p99 = models.CharField(max_length=254, verbose_name="9.  Quel est le plus grand problème / défi majeur que vous rencontrez depuis que vous exercez cette activité ?", null=True)
    p100 = models.CharField(max_length=254, verbose_name="9.  Que proposez-vous comme piste de solution pour l’amélioration des conditions des commerçants de rue ?", null=True)
    p101 = models.CharField(max_length=254, verbose_name="9.  Dans le cadre du projet Informa’ll City Move, nous aimerions organiser une base de données des commerçants de rue au centre-ville. Seriez-vous intéressez à figurer dans cette base de données afin de servir de point de contact ?", null=True)
    p102 = models.CharField(max_length=254, verbose_name="9.  Nom :", null=True)
    p103 = models.CharField(max_length=254, verbose_name="9.  Numéro de téléphone :", null=True)
    geom = models.PointField(srid=4326, null=True)

    def _unicode_(self):
        return self.p102

    def __str__(self):
        return self.p102
